blank_issues_enabled: true
contact_links:
    - name: 🚀 Feature Request
      url: https://roadmap.openpanel.com/
      about: Request new features or vote on existing suggestions to help us prioritize.
    - name: 💬 Support Question
      url: https://community.openpanel.org/t/openpanel
      about: We would love to hear what you are thinking about. What can we do better? This is the place for you to vote, discuss and share ideas.
