name: Build and Push Apache Docker Image

on:
  push:
    paths:
      - 'docker/apache/**'
  pull_request:
    paths:
      - 'docker/apache/**'

jobs:
  build-and-push-apache:
    runs-on: ubuntu-latest

    env:
      DOCKER_BUILDKIT: 1

    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]  # Build for both x86_64 and ARM

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Apache image
      uses: docker/build-push-action@v3
      with:
        context: ./docker/apache
        push: true
        tags: openpanel/apache:latest
        platforms: ${{ matrix.platform }}  # Specify the platform from the matrix
