name: GitHub Issues to Discord
on:
  issues:
    types: [labeled]

jobs:
  notify-discord:
    if: github.event.label.name == 'bug'
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\": \"🐞 **New [BUG] issue reported:** ${{ github.event.issue.title }}\n🔗 ${{ github.event.issue.html_url }}\"}" \
          "${{ secrets.DISCORD_WEBHOOK }}"
