name: GitHub Issues to Discord
on:
  issues:
    types: [opened]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\": \"📢 **New issue reported:** ${{ github.event.issue.title }}\n🔗 ${{ github.event.issue.html_url }}\"}" \
          "${{ secrets.DISCORD_WEBHOOK }}"
