name: Hourly Job

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  hourly-tasks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Restore demo site
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
        run: |
          chmod +x ./demo/restore-snapshot.sh
          ./demo/restore-snapshot.sh
